version: '3'
services:
  graph-node:
    image: graphprotocol/graph-node:v0.34.1
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    expose:
      - 8000
      - 8001
      - 8020
      - 8030
    depends_on:
      - ipfs
      - postgres
    environment:
      postgres_host: postgres
      postgres_user: postgres
      postgres_pass: postgres
      postgres_db: postgres
      ipfs: 'ipfs:5001'
      # Change next line if you want to connect to a different JSON-RPC endpoint
      ethereum: 'mainnet:https://mainnet-dev.sovryn.app/rpc'
      GRAPH_LOG: 'info'
      GRAPH_GRAPHQL_QUERY_TIMEOUT: '10'
      GRAPH_SQL_STATEMENT_TIMEOUT: '10'
      GRAPH_GRAPHQL_MAX_DEPTH: '16'
      GRAPH_GRAPHQL_MAX_COMPLEXITY: '1500000'
    restart: 'always'
  ipfs:
    image: ipfs/go-ipfs:latest
    ports:
      - '5001:5001'
    expose:
      - 5001
    volumes:
      - ./data/ipfs:/data/ipfs
  postgres:
    image: postgres:14
    ports:
      - '5432:5432'
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
